name: Otomatik Fiyat Guncelleme
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install requests beautifulsoup4
      - name: Run Scraper
        env:
          SCRAPER_API_KEY: ${{ secrets.SCRAPER_API_KEY }} # Burası çok önemli
        run: python scraper.py
      - run: |
          git config --global user.name 'Techeck Bot'
          git config --global user.email 'bot@techeck.com'
          git add updates.json
          git commit -m "Fiyatlar ScraperAPI ile guncellendi" || exit 0
          git push
