name: Otomatik Fiyat Guncelleme
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Repo kopyalanıyor
        uses: actions/checkout@v4 # v2'den v4'e güncellendi
      
      - name: Python kuruluyor
        uses: actions/setup-python@v5 # v2'den v5'e güncellendi
        with:
          python-version: '3.11'
          
      - name: Paketler yukleniyor
        run: pip install requests beautifulsoup4
        
      - name: Scraper calistiriliyor
        run: python scraper.py
        
      - name: Degisiklikler kaydediliyor
        run: |
          git config --global user.name 'Techeck Bot'
          git config --global user.email 'bot@techeck.com'
          git add updates.json
          git commit -m "Fiyatlar otomatik guncellendi" || exit 0
          git push
